# -*- coding: utf-8 -*-
"""Style~Sense.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYSliz9UJWVgP7nPU8Uy3-cU3IZjpVLg
"""

# StyleSense - Fashion Recommendation AI

print("Welcome to StyleSense")

!pip install transformers

!pip install opencv-python mediapipe numpy pillow

from google.colab import files

uploaded = files.upload()

import cv2
import numpy as np
from PIL import Image

# Load uploaded image
img_path = list(uploaded.keys())[0]
img = cv2.imread(img_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Convert to grayscale for face detection
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Use OpenCV built-in face detector
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
)

faces = face_cascade.detectMultiScale(gray, 1.3, 5)

if len(faces) == 0:
    print("No face detected")
else:
    x,y,w,h = faces[0]

    face = img_rgb[y:y+h, x:x+w]

    # Estimate average color
    avg_color = np.mean(face.reshape(-1,3), axis=0)

    print("Estimated skin RGB:", avg_color)

    # Simple tone classification
    brightness = np.mean(avg_color)

    if brightness > 170:
        tone = "Light"
    elif brightness > 120:
        tone = "Medium"
    else:
        tone = "Deep"

    print("Detected tone:", tone)

# Color recommendation based on detected tone

def recommend_colors(tone):
    if tone == "Light":
        return ["Navy Blue", "Emerald Green", "Burgundy", "Charcoal"]

    if tone == "Medium":
        return ["Olive", "Mustard", "Teal", "Maroon"]

    if tone == "Deep":
        return ["Royal Blue", "Crimson", "Gold", "Purple"]

colors = recommend_colors(tone)

print("Recommended clothing colors:")
for c in colors:
    print("-", c)

!pip install diffusers transformers accelerate safetensors

import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5"
)

pipe = pipe.to("cuda")

prompt = f"fashion outfit for {tone} skin tone person, stylish clothing, studio photo"

image = pipe(prompt).images[0]

display(image)

occasion = input("Enter occasion (wedding, party, interview, casual, etc): ")
print("Occasion:", occasion)

gender = input("Enter gender (male/female): ")

smart_prompt = f"""
Professional fashion photography,
ONE full body adult {gender} model ONLY,
solo portrait,
wearing {colors[0]} outfit,
suitable for {occasion},
no other people,
designed for {tone} skin tone,
trendy styling,
high detail clothing,
realistic lighting
"""

images = pipe(
    smart_prompt,
    negative_prompt="""
blurry, distorted face, extra people,
low quality, bad anatomy, faded skin,
deformed eyes, bad proportions
""",
    num_images_per_prompt=3,
    num_inference_steps=40,
    guidance_scale=8
).images

for img in images:
    display(img)

!pip install gradio opencv-python pillow

import gradio as gr
import numpy as np
from PIL import Image
import cv2

# -------- Outfit Intelligence --------

def suggest_colors(skin_tone):
    if skin_tone == "light":
        return ["navy blue", "maroon", "emerald"]
    elif skin_tone == "medium":
        return ["teal", "mustard", "royal blue"]
    else:
        return ["cream", "gold", "bright red"]


def cultural_outfit(country, occasion, gender):
    if country.lower() == "india":
        if occasion.lower() == "wedding":
            return "saree" if gender=="Female" else "sherwani"
        if occasion.lower() == "party":
            return "lehenga" if gender=="Female" else "kurta"
    return "modern stylish outfit"


# -------- Skin Tone Detection --------

def detect_skin_tone(img):
    img = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
    avg = img.mean()

    if avg > 170:
        return "light"
    elif avg > 120:
        return "medium"
    else:
        return "dark"


# -------- Main AI Function --------

def fashion_ai(image, occasion, country, gender):

    if image is None:
        return None, "Upload image first"

    tone = detect_skin_tone(image)
    colors = suggest_colors(tone)
    outfit = cultural_outfit(country, occasion, gender)

    smart_prompt = f"""
    professional fashion photography,
    full body {gender},
    wearing {colors[0]} {outfit},
    suitable for {occasion} in {country},
    realistic lighting,
    high detail clothing
    """

    images = pipe(
        smart_prompt,
        negative_prompt="blurry, low quality, extra people",
        num_images_per_prompt=2,
        num_inference_steps=35,
        guidance_scale=8
    ).images

    return images, f"""
Detected Skin Tone: {tone}
Suggested Outfit: {outfit}

Prompt Used:
{smart_prompt}
"""


# -------- Interface --------

demo = gr.Interface(
    fn=fashion_ai,
    inputs=[
        gr.Image(type="pil"),
        gr.Textbox(label="Occasion"),
        gr.Textbox(label="Country"),
        gr.Radio(["Male","Female"], label="Gender")
    ],
    outputs=[
        gr.Gallery(),
        gr.Textbox()
    ],
    title="StyleSense — AI Fashion Generator"
)

demo.launch(share=True)

import gradio as gr
import numpy as np
import cv2

# ---------- Helpers ----------

def detect_skin_tone(img):
    img = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
    avg = img.mean()

    if avg > 170:
        return "light"
    elif avg > 120:
        return "medium"
    else:
        return "dark"


def auto_outfit(occasion):
    occasion = occasion.lower()

    if "wedding" in occasion:
        return "traditional indian wedding outfit"
    if "party" in occasion:
        return "stylish modern party wear"
    if "office" in occasion:
        return "formal professional wear"
    if "festival" in occasion:
        return "colorful cultural festive wear"

    return "trendy casual outfit"


# ---------- Main Engine ----------

def stylesense(image, occasion, user_prompt):

    if image is None:
        return None, "Please upload image"

    tone = detect_skin_tone(image)
    outfit = auto_outfit(occasion)

    # ---- Gender Hint Logic ----
    text = (occasion + " " + user_prompt).lower()

    if "male" in text or "man" in text or "boy" in text:
        gender_hint = "male model"
    elif "female" in text or "woman" in text or "girl" in text:
        gender_hint = "female model"
    else:
        gender_hint = "same gender as input photo"

    # ---- Prompt ----
    smart_prompt = f"""
    professional fashion photography,
    full body {gender_hint},
    wearing {outfit},
    suited for {tone} skin tone,
    {user_prompt},
    highly detailed clothing,
    realistic lighting
    """

    images = pipe(
        smart_prompt,
        negative_prompt="blurry, distorted, extra people, low quality",
        num_images_per_prompt=2,
        num_inference_steps=35,
        guidance_scale=8
    ).images

    return images, f"""
Detected Skin Tone: {tone}
Chosen Outfit: {outfit}
Gender Hint: {gender_hint}

Prompt Used:
{smart_prompt}
"""


# ---------- Interface ----------

demo2 = gr.Interface(
    fn=stylesense,
    inputs=[
        gr.Image(type="pil"),
        gr.Textbox(label="Occasion"),
        gr.Textbox(label="Optional Style Prompt")
    ],
    outputs=[
        gr.Gallery(),
        gr.Textbox()
    ],
    title="StyleSense — Smart AI Stylist"
)

demo2.launch(share=True)

!pip install deepface

import gradio as gr
import numpy as np
import cv2
from deepface import DeepFace


# ---------- Helpers ----------

def detect_skin_tone(img):
    img = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
    avg = img.mean()

    if avg > 170:
        return "light"
    elif avg > 120:
        return "medium"
    else:
        return "dark"


def detect_gender(img):
    try:
        result = DeepFace.analyze(
            np.array(img),
            actions=['gender'],
            enforce_detection=False
        )
        g = result[0]['dominant_gender']

        # Convert to diffusion-friendly wording
        if g.lower() == "man":
            return "male model"
        elif g.lower() == "woman":
            return "female model"
        else:
            return "person"

    except:
        return "person"


def auto_outfit(occasion):
    occasion = occasion.lower()

    if "wedding" in occasion:
        return "traditional indian wedding outfit"
    if "party" in occasion:
        return "stylish modern party wear"
    if "office" in occasion:
        return "formal professional wear"
    if "festival" in occasion:
        return "colorful cultural festive wear"

    return "trendy casual outfit"


# ---------- Main Engine (WOW VERSION) ----------

def stylesense(image, occasion, user_prompt):

    if image is None:
        return None, "Please upload image"

    # ---- Auto defaults ----
    if not occasion:
        occasion = "daily wear"
    if not user_prompt:
        user_prompt = "day and night suitable styling"

    tone = detect_skin_tone(image)
    gender = detect_gender(image)
    outfit = auto_outfit(occasion)

    # ---- 3 Style Variations ----
    style_modes = [
        "traditional elegant styling",
        "modern fashionable styling",
        "premium luxury designer styling"
    ]

    generated_images = []

    for mode in style_modes:

        smart_prompt = f"""
        professional fashion photography,
        full body {gender},
        complete styled outfit,

        Topwear matching {outfit},
        Bottomwear coordinated with top,
        Stylish footwear,
        Matching belt and watch,
        Appropriate accessories and jewelry,
        Fashionable hairstyle,

        {mode},

        suited for {tone} skin tone,
        occasion: {occasion},
        extra request: {user_prompt},

        highly detailed fabric textures,
        sharp focus,
        realistic lighting,
        magazine quality fashion shoot
        """

        imgs = pipe(
            smart_prompt,
            negative_prompt="blurry, distorted, extra people, low quality",
            num_images_per_prompt=1,
            num_inference_steps=35,
            guidance_scale=8
        ).images

        generated_images.extend(imgs)

    # ---- Explainable AI Reasoning ----
    explanation = f"""
AI Styling Explanation

• Skin Tone Detected: {tone}
• Gender Detected: {gender}
• Occasion: {occasion}

Why these outfits work:
✓ Colors selected to complement your skin tone
✓ Accessories added for complete fashion styling
✓ Outfit adapted to cultural/occasion context
✓ Generated Traditional, Modern, and Premium options
✓ Designed for both daytime & evening suitability

This demonstrates AI-driven personalized fashion intelligence.
"""

    return generated_images, explanation


    # ----- Auto Mode if blank -----
    if occasion.strip() == "" and user_prompt.strip() == "":
        smart_prompt = f"""
professional fashion photography,
full body {gender},

DAY LOOK:
casual stylish daytime outfit,
topwear, bottomwear, footwear, accessories

NIGHT LOOK:
elegant evening fashion styling,
complete coordinated clothing,
shoes, watch, jewelry

suited for {tone} skin tone,
high detail clothing texture,
sharp focus,
realistic lighting
"""
    else:
        smart_prompt = f"""
professional fashion photography,
full body {gender},
complete styled outfit,

Topwear matching {outfit},
Bottomwear coordinated,
Stylish footwear,
Matching belt and watch,
Layered accessories,
Fashion hairstyle,
high fashion styling,

suited for {tone} skin tone,
occasion: {occasion},
style request: {user_prompt},

ultra detailed fabric,
8k fashion photography,
sharp focus,
realistic lighting,
magazine editorial quality
"""

    images = pipe(
        smart_prompt,
        negative_prompt="""
blurry face,
bad anatomy,
extra people,
duplicate body,
distorted eyes,
washed skin,
low resolution,
grainy
""",
        num_images_per_prompt=2,
        num_inference_steps=40,
        guidance_scale=9
    ).images

    return images, f"""
Detected Skin Tone: {tone}
Detected Gender: {gender}
Chosen Outfit: {outfit}

Prompt Used:
{smart_prompt}
"""


# ---------- Interface ----------

demo3 = gr.Interface(
    fn=stylesense,
    inputs=[
        gr.Image(type="pil"),
        gr.Textbox(label="Occasion (optional)"),
        gr.Textbox(label="Optional Style Prompt")
    ],
    outputs=[
        gr.Gallery(),
        gr.Textbox()
    ],
    title="StyleSense — AI Cultural Stylist"
)

demo3.launch(share=True)